### ISSUE TITLE
[Feature Request] Make detected links tappable

### ISSUE THREAD

**Issue by mralexhay** [gonzalezreal/swift-markdown-ui#100]
This is brilliant, thanks for making it. 

The only small thing I'm missing vs Apple's (inferior!) native markdown support is having links detected in the text (that aren't marked up) tappable. 

For example it would be great in [this image](https://imgur.com/a/jfoR6Sd) if the image URL was tappable.

Thanks!

**Comment by gonzalezreal** [comment]
Hi @mralexhay,

Sorry for the late response. That feature is part of the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/), and MarkdownUI supports the [CommonMark Spec](https://spec.commonmark.org/). That is a major change and, at the moment, I have no plans to do it.

**Comment by gonzalezreal** [comment]
Solved in MarkdownUI 2:
https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.0
