### ISSUE TITLE
Support for WatchOS

### ISSUE THREAD

**Issue by oco-adam** [gonzalezreal/swift-markdown-ui#139]
Hi,

First of all, thanks very much for the great library!

WatchOS support would be very helpful for us - do you have any plans to support WatchOS in the near future?

Thanks,
Adam

**Comment by gonzalezreal** [comment]
Perhaps 😄. MarkdownUI 1.x uses a `NS/UITextView` under the hood, which is not supported in watchOS. I am working on a new version that uses pure SwiftUI views to render the markdown. I can't promise anything yet but, hopefully, this new version could add watchOS support.

**Comment by gonzalezreal** [comment]
I can confirm that the upcoming MarkdownUI 2.0 will support watchOS 🎉.

See #169 and #152

**Comment by gonzalezreal** [comment]
MarkdownUI 2 has been released so we can close this issue.
https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.0
