### ISSUE TITLE
onTapGesture

### ISSUE THREAD

**Issue by Rukenshia** [gonzalezreal/swift-markdown-ui#161]
I have a `Markdown` view in my project and would like to switch to an editing mode when you click on it, but `onTapGesture` is not getting called when I click on the rendered view.
Is there another way of achieving this?

**Comment by gonzalezreal** [comment]
Could you please try if you can reproduce this issue in the latest release?
https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.0

If this is still the case, please let me know. Otherwise, I'd appreciate if you close this issue.

**Comment by Rukenshia** [comment]
thank you, works perfectly now!
