### ISSUE TITLE
Index out of range issue from AttributedText dependency

### ISSUE THREAD

**Issue by yczeng** [gonzalezreal/swift-markdown-ui#165]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/21347461/206349927-0849257b-28a2-4a66-9f06-a3d3d0769611.png">
<img width="882" alt="image" src="https://user-images.githubusercontent.com/21347461/206349960-adb7439f-5f46-4139-bbde-7199332346ce.png">

**Comment by gonzalezreal** [comment]
Hi @yczeng,

MarkdownUI 2 no longer uses this dependency. See the release notes:
https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.0

In any case, this issue should belong to AttributedText and not to swift-markdown-ui.
