### ISSUE TITLE
Inline image in text in Markdown not shown

### ISSUE THREAD

**Issue by huber-florian** [gonzalezreal/swift-markdown-ui#185]
**Describe the bug**
Prior to the newest major release, it was possible to embed images directly in the text. Since the major update it does not work any more.

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Markdown("2.\n\n ![This is](TestFailedSymbol) \n\n**Context Class (2 of 2 tests passing)** ").markdownImageProvider(.asset)
            Markdown("2.\n ![This is](TestFailedSymbol) \n\n**Context Class (2 of 2 tests passing)** ").markdownImageProvider(.asset)
            Markdown("2.\n\n ![This is](TestFailedSymbol) \n**Context Class (2 of 2 tests passing)** ").markdownImageProvider(.asset)
            Markdown("2.  ![This is](TestFailedSymbol)  **Context Class (2 of 2 tests passing)** ").markdownImageProvider(.asset)
            Markdown("2.  ![This is](TestFailedSymbol) **Context Class (2 of 2 tests passing)** ").markdownImageProvider(.asset)
            Markdown("2. ![This is](TestFailedSymbol) **Context Class (2 of 2 tests passing)** ").markdownImageProvider(.asset)

(The "This is" part from above: ! [This is] (TestFailedSymbol)           )(without spaces!)
(The last 3 statements have a different amount of whitespaces to test if that changes something.)

**Expected behavior**
The expected behavior would be that in all six cases the TestFailedSymbol is shown. (Works also with the dog image of the given example.) But only in the first two cases the image is shown.
The second screenshot shows that it was possible to embed an image within the text prior to this major update.

**Screenshots**
Experiments now (version 2.0.0):
<img width="277" alt="image" src="https://user-images.githubusercontent.com/116847304/215608686-145e7dc1-c19f-41b3-866c-f02d69c69e84.png">

Well working solution before (version 1.x):
![image](https://user-images.githubusercontent.com/116847304/215608840-e7cdc19e-eca9-4c8b-8cd7-790695c96c26.png)

**Version information**
- MarkdownUI: [2.0.0]
- OS: [iOS 16.2, macOS 13.2]
- Xcode: [14.2.0]

**Comment by gonzalezreal** [comment]
Hi @huber-florian,

Thanks for reporting this issue. It is a side-effect of re-implementing the Markdown rendering with SwiftUI primitives. I have some ideas to fix it for this particular use case. Unfortunately, other use cases, like images inside links with inline text, are impossible to fix until Apple correctly supports images in `AttributedString`.

https://swiftpackageindex.com/gonzalezreal/swift-markdown-ui/2.0.0/documentation/markdownui/inlineimage

**Comment by gonzalezreal** [comment]
Hi @huber-florian,

The fix for this issue is now available in the main branch. Please take a look at the Demo project in the **Images** and **Image Providers** screens for the inline image support and the new `markdownInlineImageProvider` modifier.

**Comment by huber-florian** [comment]
Thank you @gonzalezreal !
