### ISSUE TITLE
markdownInlineImageProvider not found 

### ISSUE THREAD

**Issue by panviktor** [gonzalezreal/swift-markdown-ui#195]
**Screenshots**

**Version information**
- MarkdownUI: [e.g. 2.0.1, or a commit hash]
- OS: [e.g. iOS 15, macOS 13]
- Xcode: [e.g. 14.2.0]

**Additional context**
Can't find markdownInlineImageProvider after import your  package. 

<img width="630" alt="Screenshot 2023-02-28 at 20 44 32" src="https://user-images.githubusercontent.com/35385675/221920129-a11db338-7b5f-48b7-b0b7-57ecee699b7a.png">

**Comment by gonzalezreal** [comment]
This modifier has not been released yet. It's only on the main branch. Could you please provide more info to reproduce this issue?

**Comment by gonzalezreal** [comment]
Closing as invalid.
