### ISSUE TITLE
The Demo project does not run

### ISSUE THREAD

**Issue by randomsnowflake** [gonzalezreal/swift-markdown-ui#199]
I downloaded the repository and opened the Examples/Demo project file in the newest Xcode.

While the build (for all platforms) succeeds, running the app doesn't do anything. No binary is generated.

Also, when opening the SwiftUI views, the Canvas displays "Cannot preview in this file - Active scheme does not build this file".

**Comment by gonzalezreal** [comment]
Have you selected the correct scheme?

You need to select the `Demo` scheme to run the demo. Once you choose the scheme, everything should work fine, including previews.

![Screenshot 2023-03-13 at 10 15 15](https://user-images.githubusercontent.com/373190/224657838-ece6567c-8a08-4b8e-a9eb-e58079367e32.png)

**Comment by randomsnowflake** [comment]
Yes, that was it. Thanks.
