### ISSUE TITLE
The deprecation warning for onOpenMarkdownLink seems incorrect

### ISSUE THREAD

**Issue by tkirby** [gonzalezreal/swift-markdown-ui#207]
**Describe the bug**
The deprecation warning for onOpenMarkdownLink seems to be incorrect. The message suggests that "MarkdownImageHandler" has been superseded by the "ImageProvider" protocol and its conforming types "DefaultImageProvider" and "AssetImageProvider", which is not relevant to onOpenMarkdownLink.

**Checklist**

- [x ]  I can reproduce this issue with a vanilla SwiftUI project.
- [x ]  I can reproduce this issue using the main branch of this package.
- [ x]  This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

 
**Steps to reproduce**

1. Create a SwiftUI project.
2. Add a markdown view to the project.
3. Implement onOpenMarkdownLink method in the view.
4. Observe the deprecation warning for onOpenMarkdownLink.

**Expected behavior**
The deprecation warning for onOpenMarkdownLink should provide relevant information related to the deprecation and point to what has replaced it if applicable.

Screenshots
N/A

Version information

MarkdownUI: 2.0.2
OS: iOS 15

**Comment by gonzalezreal** [comment]
Thanks for raising this documentation issue.
