### ISSUE TITLE
When i'm trying to use MarkdownUI in LazyVStack inside a ScrollView, The page cannot scroll and the layout is shaking up and down.

### ISSUE THREAD

**Issue by CoderLineChan** [gonzalezreal/swift-markdown-ui#209]
**Describe the bug**
When I generate a long article, MarkdownUI keeps shaking and cannot scroll.

**some code**
```
struct ChatRoomView: View {
    var body: some View {
        GeometryReader { geometry in
            VStack(spacing: 0) {
                ScrollView {
                    ScrollViewReader { scrollView in
                        LazyVStack(alignment: .trailing, spacing: 8) {
                            ForEach(messages, id: \.id) { message in
                                ChatRoomCellView(message: message)
                                    .id(message.id)
                            }
                        }
                    }
                    .background(Color.clear)
                }
                .frame(maxHeight: geometry.size.height)
                Divider()
                    ......
            }
        }
    }
}

struct ChatRoomCellView: View {
    let message: Message
    @Environment(\.colorScheme) private var colorScheme
    var body: some View {
        HStack {
            if message.role != "gpt" {
                Spacer()
                VStack {
                    Text(message.text ?? "")
                        .textSelection(.enabled)
                        .id(message.id)
                }
            } else {
                    DemoView {
                        Markdown(message.text ?? "")
                            .padding(12)
                            .textSelection(.enabled)
                            .markdownCodeSyntaxHighlighter(.splash(theme: codeTheme(scheme: colorScheme)))
                            .cornerRadius(6)
                    }.id(message.id)
                }
                    
                Spacer()
            }
        }
    }
}
```

**Screenshots**

https://user-images.githubusercontent.com/21659158/229860262-91993ae5-ee78-4181-82e4-6a55a28b4edd.mp4

**Version information**
- MarkdownUI: [2.0.0]
- OS: [macOS 13]
- Xcode: [14.2.0]

**Additional context**

**Comment by gonzalezreal** [comment]
Hi @CoderLineChan,

If you provide an isolated Xcode project that reproduces the issue, I can help you to pinpoint the problem.

**Comment by gonzalezreal** [comment]
Hi @CoderLineChan,

You are seeing this issue because you have multiple nested vertical scroll views. Beware that the `Form` view in your `MarkdownView` is also a vertical `ScrollView`, which collides with the main scroll view in which you are rendering the `ChatRoomCellView`s.

In short, this is not a MarkdownUI issue.

**Comment by CoderLineChan** [comment]
Because using Markdown(message.text) directly would cause problems, I added MarkdownView, and MarkdownView+Markdown is the code in your demo (MarkdownView is the DemoView in your demo) that I completely copied. Does your Markdown not support using it in vertical scrolling?

**Comment by kchro3** [comment]
@gonzalezreal , I think that I am running into a similar issue, but I'd love to get your assistance.

**Comment by gonzalezreal** [comment]
@kchro3 Please provide a working Xcode project reproducing the issue, and I will investigate it.

**Comment by AugustDev** [comment]
What would be the right way to handle `ScrollView` containing multiple vertical items of `Markdown`? Since Markdown contains scrolling it interferes with the parent scroll view and users are not able to scroll vertically when mouse hovers `Markdown` component?
