### ISSUE TITLE
Table height miscalculated

### ISSUE THREAD

**Issue by FliiFe** [gonzalezreal/swift-markdown-ui#219]
**Describe the bug**
In some cases, a table's height might not be correctly calculated, disturbing the surrounding elements

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
I used the following table.
```markdown
| Column 2 | Column 1 |
|----------|----------|
| Here's another example of a multiline text in column 2.\nI'm just adding more lines to make it longer. | This is a sample text.\nIt spans multiple lines. |
| And the content of the second column is here as well.\nI can add more lines if I want to, but I'll stop now. | The second row starts here. |
| This is a multiline text, just like the others. | Third row, first column's text. |
| Fourth row, second column. | Fourth row, first column. |
| Fifth row, second column. | Fifth row, first column. |
| Sixth row, second column. | Sixth row, first column. |
| Seventh row, second column. | Seventh row, first column. |
| Eighth row, second column. | Eighth row, first column. |
| Ninth row, second column. | Ninth row, first column. |
| Tenth row, second column. | Tenth row, first column. |
```
Adjust the window width: sometimes the height is correct, sometimes it is not.

**Expected behavior**
The Markdown view extends to the full height of the table

**Screenshots**
https://streamable.com/we218l

Look at the `Divider` view below the `Markdown` view. They are next to each other in a `VStack`.

**Version information**
- MarkdownUI: main branch
- OS: macOS 13.2.1
- Xcode: 14.3

**Comment by gonzalezreal** [comment]
Hi @FliiFe,

MarkdownUI uses SwiftUI's [Grid](https://developer.apple.com/documentation/swiftui/grid) to render tables:

https://github.com/gonzalezreal/swift-markdown-ui/blob/66dcceca0ffbb772eba5b4de19694f817820087d/Sources/MarkdownUI/Views/Blocks/TableView.swift#L16

The video shows that the `Grid` reports an incorrect height to the `VStack` when the parent view becomes too narrow. Have you tried to fix the height of the Markdown view to its ideal height?

```swift
Markdown {
  ...
}
.fixedSize(horizontal: false, vertical: true)
```

**Comment by FliiFe** [comment]
This seems to do the trick, thank you!

**Comment by gonzalezreal** [comment]
Hey @FliiFe,

The latest release includes the `fixedSize` modifier in all the bundled themes, so you should call it after upgrading.
