### ISSUE TITLE
.onLongPressGesture when it causes not to scroll

### ISSUE THREAD

**Issue by wscqs** [gonzalezreal/swift-markdown-ui#227]
ScrollView{
        VStack{
            Markdown(content)
                .onLongPressGesture(perform: {
                })
        }
    }

GestureOnMarkdownCell  causes scrollview can not  scroll

**Comment by gonzalezreal** [comment]
I am pretty sure the same will happen with any other view, for instance, `Text`. This post may help:
https://danielsaidi.com/blog/2022/11/16/using-complex-gestures-in-a-scroll-view

Please, consider using the provided template when opening an issue and fill in all the relevant information. In the future, I may overlook or completely ignore issues without the required information, as it is very time-consuming to guess the actual problem.
