### ISSUE TITLE
How do I get the height of the Markdown change

### ISSUE THREAD

**Issue by wscqs** [gonzalezreal/swift-markdown-ui#230]
struct ContentView: View {
    var body: some View {
        Text("Hello, World!") //Markdown
            .background(GeometryReader { geometry in
                Color.clear
                    .preference(key: ViewHeightKey.self, value: geometry.size.height)
            })
            .onPreferenceChange(ViewHeightKey.self) { height in
                print("The view height is: \(height)") //Markdown all is 0
            } 
    }
}

struct ViewHeightKey: PreferenceKey {
    static var defaultValue: CGFloat = 0
    static func reduce(value: inout CGFloat, nextValue: () -> CGFloat) {
        value = nextValue()
    }
}

**Comment by xiaomage1478** [comment]
> 我有一个需求是：ai回复是拼markdown的，一个字一个字的然后一直在底部滚动的需求，所以希望能接受markdown高度变化回调

你好兄弟，这个问题你解决了吗，我有遇到过，交流一下

**Comment by wscqs** [comment]
> > 我有一个需求是：ai回复是拼markdown的，一个字一个字的然后一直在底部滚动的需求，所以希望能接受markdown高度变化回调
> 
> 你好兄弟，这个问题你解决了吗，我有遇到过，交流一下

自己解决方案不好，不准确。  还是等作者看能不能弄个回调

**Comment by gonzalezreal** [comment]
Closing this as invalid. Please use [Discussions](https://github.com/gonzalezreal/swift-markdown-ui/discussions) for questions, ideas and feature requests.
