### ISSUE TITLE
render text too height

### ISSUE THREAD

**Issue by yonghuming** [gonzalezreal/swift-markdown-ui#250]
Thank you for contributing to MarkdownUI!

Before you submit an issue, please complete the report with all the relevant details for your bug and go through every item in the checklist.

**Describe the bug**
the Markdown view is too high
<img width="345" alt="image" src="https://github.com/gonzalezreal/swift-markdown-ui/assets/435079/936c4455-63e3-4a6a-bf00-4829865a67c6">

```
//
//  ContentView.swift
//  MD3
//
//  Created by meng xianlang on 2023/8/17.
//

import SwiftUI
import MarkdownUI

struct ContentView: View {
    let markdownString = """
      ## Try MarkdownUI

      **MarkdownUI** is a native Markdown renderer for SwiftUI
      compatible with the
      [GitHub Flavored Markdown Spec](https://github.github.com/gfm/).
      """

    var body: some View {
      Markdown(markdownString)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```

**Checklist**
- [ ] I can reproduce this issue with a vanilla SwiftUI project.
- [ ] I can reproduce this issue using the `main` branch of this package.
- [ ] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Explanation of how to reproduce the incorrect behavior. This could include an attached project, a link to code, or a Markdown-formatted text exhibiting the issue.
1. ...

**Expected behavior**

**Screenshots**

**Version information**
- MarkdownUI: [e.g. 2.0.0, or a commit hash]
- OS: [e.g. iOS 15, macOS 13]
- Xcode: [e.g. 14.2.0]

**Additional context**

**Comment by gonzalezreal** [comment]
Closing due to unclear and incomplete report.

**Comment by yonghuming** [comment]
您好，邮件已经收到
