### ISSUE TITLE
Code blocks get truncated

### ISSUE THREAD

**Issue by moophis** [gonzalezreal/swift-markdown-ui#251]
**Describe the bug**
When a markdown string contains multiple code blocks and if one of them contains more lines (e.g., 35+ lines of code), other code texts get truncated (with `...` at the end of the text). See detailed repro steps below.

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Apply this [sample text](https://gist.github.com/moophis/1bc93a3b8dd8d3a42e5efa34e0af3281) which contains a couple of code blocks with the last one being the longest to the Demo app `CodeSyntaxHighlightView`.

**Expected behavior**
All code should be fully visible and no extra top and bottom padding should be applied around the `Markdown` view. I suspect that the extra paddings are otherwise reserved for these hidden code blocks.

**Screenshots**
See truncated code texts with `...` and extra vertical paddings.
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-08-25 at 21 30 03](https://github.com/gonzalezreal/swift-markdown-ui/assets/2663719/a403d871-6077-430e-ab39-c90c92391d3a)
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-08-25 at 21 30 11](https://github.com/gonzalezreal/swift-markdown-ui/assets/2663719/19996a2c-49ee-4c76-9db3-0ba04e85dead)
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-08-25 at 21 30 15](https://github.com/gonzalezreal/swift-markdown-ui/assets/2663719/5a7351ed-c205-47c0-ac1e-aa8dace578a9)

https://github.com/gonzalezreal/swift-markdown-ui/assets/2663719/5f8a9301-e72c-4cb6-b1a6-598eb8cb629d

**Version information**
- MarkdownUI: [main / 2.1.0]
- OS: [iOS 16.1, macOS 13.4.1]
- Xcode: [14.1.0]

**Comment by gonzalezreal** [comment]
Hi @moophis,

Thanks for reporting this. The fix is on its way.

**Comment by gonzalezreal** [comment]
The fix has been released in [MarkdownUI 2.2.0](https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.2.0)
