### ISSUE TITLE
Ambiguous use of 'init(light:dark:)

### ISSUE THREAD

**Issue by iTarek** [gonzalezreal/swift-markdown-ui#265]
With the new XCode I can not use init(light:dark:) on my own custom theme I get error

`Ambiguous use of 'init(light:dark:)'
`
![Screenshot 2023-10-07 at 2 04 40 AM](https://github.com/gonzalezreal/swift-markdown-ui/assets/693715/f811a618-4325-4df1-b99c-d5d0f36153a8)

It was working good before I update my XCode also updated to the latest swift-markdown-ui. Any solution?

**Comment by gonzalezreal** [comment]
Hey @iTarek,

I cannot reproduce that issue. Could it be that you have the same extension on `Color` but introduced by another dependency, causing the ambiguity?

**Comment by alex-vasenin** [comment]
I have the same issue. I have extension `Color.init(light:dark:)` defined in my app and it conflicts with the one that MarkdownUI exposes publicly. There is no way to disambiguate those without changing the method signature. Could you please make it `internal`? I don't think it's intended to be public in the first place.
