### ISSUE TITLE
Table rendering issue on iOS15

### ISSUE THREAD

**Issue by syegin** [gonzalezreal/swift-markdown-ui#277]
**Describe the bug**
Tables are not being rendered properly on iOS 15, it just renders the raw markdown text. looks working fine on iOS 16 and 17.

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
1. Realized this issue on my project. But it's also happening for demo project on main branch. (Deployment target for demo project is 16, so i downgraded it to 15 and commented out everything giving error so that i can run the project.)

**Expected behavior**
Should be able to render tables on iOS 15.

**Screenshots**
![Simulator Screenshot - iPhone SE (3rd generation) - 2023-11-23 at 11 33 49](https://github.com/gonzalezreal/swift-markdown-ui/assets/5259684/55093050-66b1-4670-bfd8-3d8af313cd86)

**Version information**
- MarkdownUI: 2.0.1 & 2.1.0 & 2.2.0
- OS: iOS 15
- Xcode: 14.2 & 15.0.1

**Comment by syegin** [comment]
Ok now i've just seen the note, tables are not supported on iOS 15. 
So my question what is the reason there is no support, is it causing any issue while rendering?

**Comment by gonzalezreal** [comment]
Hi @syegin,

Thanks for raising this issue. This is a known limitation, even documented in the [Minimum Requirements](https://github.com/gonzalezreal/swift-markdown-ui#minimum-requirements) section of the README.

The current table implementation uses a [Grid](https://developer.apple.com/documentation/swiftui/grid) view, only available from iOS 16, macOS 13, tvOS 16, and watchOS 9.

I am experimenting with other approaches to lay out the text that may enable table rendering on iOS 15 and fix other issues. But I can't promise anything at the moment.
