### ISSUE TITLE
How can I change the background colour of downView? Also the text loading seems very big than normal. How can I set the font size and background colour? Please help

### ISSUE THREAD

**Issue by jaisan03** [gonzalezreal/swift-markdown-ui#292]
Thank you for contributing to MarkdownUI!

Before you submit an issue, please complete the report with all the relevant details for your bug and go through every item in the checklist.

**Describe the bug**

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Explanation of how to reproduce the incorrect behavior. This could include an attached project, a link to code, or a Markdown-formatted text exhibiting the issue.
1. ...

**Expected behavior**

**Screenshots**

**Version information**
- MarkdownUI: [e.g. 2.0.0, or a commit hash]
- OS: [e.g. iOS 15, macOS 13]
- Xcode: [e.g. 14.2.0]

**Additional context**

**Comment by jaisan03** [comment]
`
![Uploading Simulator Screen Shot - iPhone 8 Plus - 2024-01-17 at 21.52.52.png…]()
`

**Comment by gonzalezreal** [comment]
Closing as invalid. Please, consider opening a [discussion](https://github.com/gonzalezreal/swift-markdown-ui/discussions) with your questions.
