### ISSUE TITLE
Weird space on a new line in a very complex app

### ISSUE THREAD

**Issue by tzdesign** [gonzalezreal/swift-markdown-ui#294]
**Describe the bug**

I put a big chunk of markdown in the `Markdown` view and it looks like that every single new line get's a small space up front.

If I create a complete new App and copy the API Text in The `Markdown` view, this is not happening.

**Screenshots**

Left the fresh new app / right the big old one

<img width="298" alt="Bildschirmfoto 2024-01-26 um 15 04 22" src="https://github.com/gonzalezreal/swift-markdown-ui/assets/3037096/066d01ff-6bf7-4b2d-99e5-758aced121da">

Marked spaces:

<img width="383" alt="Bildschirmfoto 2024-01-26 um 15 04 09" src="https://github.com/gonzalezreal/swift-markdown-ui/assets/3037096/66d5fa41-3f39-4572-8257-871e695f9df9">

**Version information**
- MarkdownUI: [e.g. 2.3.0]
- OS: [e.g. iOS 16.6]
- Xcode: [e.g. 15.2]

**Comment by gonzalezreal** [comment]
Hi @tzdesign,

Could you please provide a project that reproduces the issue? Otherwise, I can't help you with this.

**Comment by tzdesign** [comment]
Sorry, but I wasn't able to.

I have a very complex view structure. I will checkout the markdown project myself and try to find out where they are comping from.

You can close it and I will write here if I can find any clues.
