### ISSUE TITLE
Xcode 16 beta 4- Compile Error Circular Reference

### ISSUE THREAD

**Issue by PriyaChopra11** [gonzalezreal/swift-markdown-ui#340]
Thank you for contributing to MarkdownUI!

Before you submit an issue, please complete the report with all the relevant details for your bug and go through every item in the checklist.

**Describe the bug**

**Checklist**
- [ ] I can reproduce this issue with a vanilla SwiftUI project.
- [ ] I can reproduce this issue using the `main` branch of this package.
- [ ] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Explanation of how to reproduce the incorrect behavior. This could include an attached project, a link to code, or a Markdown-formatted text exhibiting the issue.
1. ...

**Expected behavior**

**Screenshots**

**Version information**
- MarkdownUI: [e.g. 2.0.0, or a commit hash]
- OS: [e.g. iOS 15, macOS 13]
- Xcode: [e.g. 14.2.0]

**Additional context**

**Comment by gonzalezreal** [comment]
I cannot reproduce any compilation issue in Xcode 16 Beta 5.

**Comment by itsthisjustin** [comment]
Yeah I think this was already fixed in that one PR. I'm not longer having the issue.
