### ISSUE TITLE
Wrong font size with blank bullet list

### ISSUE THREAD

**Issue by schwindt** [gonzalezreal/swift-markdown-ui#344]
A blank bullet list leads to an incorrect font size.

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Explanation of how to reproduce the incorrect behavior. This could include an attached project, a link to code, or a Markdown-formatted text exhibiting the issue.
1. try to preview this markdown string: 
2. `"**Banana**:\n   - oink"`, this one behaves correctly
3. try this string: `"**Banana**:\n   - "`
4. In this case the word Banana will be written with much bigger font size

**Expected behavior**
It should be the same font size

**Screenshots**
<img width="663" alt="Bildschirmfoto 2024-08-22 um 14 46 06" src="https://github.com/user-attachments/assets/04389e7e-4cd3-48df-8b04-1cede24ecf07">

<img width="606" alt="Bildschirmfoto 2024-08-22 um 14 45 56" src="https://github.com/user-attachments/assets/68fe06b5-d35f-4786-91de-12dad8e86b7a">

**Version information**
- MarkdownUI: 2.3.1
- OS:  iOS 17.5
- Xcode: 15.0

**Comment by TMABC** [comment]
The library works as expected because the parsing is driven by cmark-gfm, and the results of the two parsing are different. The second resolution is heading leve2.
