### ISSUE TITLE
Issue with identifying the single line break "\n" and adding it to the end of previous line

### ISSUE THREAD

**Issue by DeepakiOS1993** [gonzalezreal/swift-markdown-ui#352]

**Comment by DeepakiOS1993** [comment]
Hi Team , great work keep going!!!!

I am facing issue when trying to render the string from web which has single line breaks and multiple line breaks

Below is the Sample of string i Am trying to render

`Example #1 - This is due to new markdown formatting/syntax because of the new iOS markdown library.
**Before MD Library Change**
You could bold the header of a paragraph and we were told not to put a space between the bold header and new paragraph (above or below the bold text), as the old markdown library added the space automatically.

Example #2 - To show the correct new iOS MD Syntax

**After MD Library Change**

If we don't put a space between the bold text, the paragraph below it, or above, it looks like the above example in your phone [iOS]. However, this example adds two spaces in the Android markdown view and is an issue they are working on now.`

To Bring to Notice there is line break after first line.

But the output which i could seen on screen is some thing similar to below 
![Simulator Screenshot - iPhone 15 Pro - 2024-10-14 at 20 39 12](https://github.com/user-attachments/assets/a0b58d9e-e2cb-4df6-b689-7d3a5c51e89d)

There should be line break before and after the bold text i.e **Before MD Library Change**
But as we see the output only shows double link breaks which is before .

the String which i want to render is something similar to 
`"Example #1 - This is due to new markdown formatting/syntax because of the new iOS markdown library.\n**Before MD Library Change**\nYou could bold the header of a paragraph and we were told not to put a space between the bold header and new paragraph (above or below the bold text), as the old markdown library added the space automatically.\n\nExample #2 - To show the correct new iOS MD Syntax\n\n**After MD Library Change**\n\nIf we don\'t put a space between the bold text, the paragraph below it, or above, it looks like the above example in your phone [iOS]. However, this example adds two spaces in the Android markdown view and is an issue they are working on now."`

Please support as using it in producation App, 
**Note :  Using as package Dependencies with SPM, And version of library 2.4.1**

**Comment by davidseek** [comment]
+1

Also experiencing issues when rendering `\n` and `\n\n`. Some line-breaks work, others are breaking.

**Comment by gonzalezreal** [comment]
Hi there,

By default, Markdown considers single line breaks `\n` inside a paragraph as soft-breaks. For reference, see the [specs](https://github.github.com/gfm/#soft-line-breaks).

Markdown renderers can choose to render a soft-break either as a space ` ` or as a newline `\n`. For instance, GitHub renders soft-breaks as spaces in Markdown files (ie. `README.md`), but it uses newlines in comments.

MarkdownUI renders soft-breaks as spaces by default, but you can tweak this behavior thanks to a recent contribution. See #342 for more information.

**Comment by gonzalezreal** [comment]
The following test might help as well:
https://github.com/gonzalezreal/swift-markdown-ui/blob/a9c7615fb50323069c2979c69263973aa1b24a8f/Tests/MarkdownUITests/MarkdownTests.swift#L325-L344
