### ISSUE TITLE
Unable to install the SwiftMarkdownUI with SPM

### ISSUE THREAD

**Issue by babyghost-ys** [gonzalezreal/swift-markdown-ui#358]
Thank you for contributing to MarkdownUI!

Before you submit an issue, please complete the report with all the relevant details for your bug and go through every item in the checklist.

**Describe the bug**
I was trying to install the Swift-Markdown-UI package via SPM, but it's showing unresolved error. I investigate a bit and I think one of the dependencies of Swift-Markdown-UI is not working. And that could be swift-cmark. I am able to build the demo project though. So if there are any way to get around this, it would be great. 

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [X] I can reproduce this issue using the `main` branch of this package.
- [X] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
Explanation of how to reproduce the incorrect behavior. This could include an attached project, a link to code, or a Markdown-formatted text exhibiting the issue.
1. Go to Xcode. Add the SPM by going to Package Dependencies
2. Add the link https://github.com/gonzalezreal/swift-markdown-ui
3. It will be showing the unresolved error

**Expected behavior**
Installing the APM as usual

**Screenshots**
<img width="1088" alt="Screenshot 2024-10-26 at 14 16 02" src="https://github.com/user-attachments/assets/69d8d2aa-759a-422a-a2ab-2407fb8466fb">

**Version information**
- MarkdownUI: 2.4.1
- OS: iOS 18 / iOS 17.6 + macOS 15.0 / macOS 15.2
- Xcode: 16.1

**Additional context**

**Comment by babyghost-ys** [comment]
I figured out a way to do temporarily fix it. It would still be nice to be able to install SPM via the link.
1. Create a new package with Xcode. Name it as "MarkdownUI"
2. Remove the original Source file.
3. Copy and paste the folder "Source" and "Test" from the original source in this git to the new package created in 1
4. Go to your own project, add files to your own project. Point to the folder we created in step 1.

**Comment by gonzalezreal** [comment]
Hi @babyghost-ys,

I cannot reproduce the issue. I created an Xcode project and added the dependency using the link without any issues.

<img width="1420" alt="Screenshot 2024-10-27 at 07 46 09" src="https://github.com/user-attachments/assets/da5d2391-8664-46cc-9083-56efbe92b3d6">
