### ISSUE TITLE
[Feature Request] Support InlineSyntax

### ISSUE THREAD

**Issue by singularity-s0** [gonzalezreal/swift-markdown-ui#96]
This library will become much more powerful if it adds support for user-defined custom syntaxes (inline syntax). 

To define these syntaxes, the developer will:
1. specify a list of Regular Expressions that matches the corresponding syntax block in the document, 
2. then specify the View that handles each block.

If you are familiar with Flutter (another declarative UI framework), [flutter_markdown](https://pub.dev/packages/flutter_markdown) provides a good example of how this works.

**Comment by gonzalezreal** [comment]
Thank you for the feedback! I will have a look at the doc you provided.
