### ISSUE TITLE
Selectable text on iOS

### ISSUE THREAD

**Issue by matiaskorhonen** [gonzalezreal/swift-markdown-ui#97]
The release notes for 1.0.0 include “Added: Make text not selectable on iOS” but I have some text that I'd like to be selectable. Is this possible? I couldn't figure it out on my own…

**Comment by gonzalezreal** [comment]
Hi @matiaskorhonen,
Sorry for the late response. This is currently not possible. I will consider this in a future release.

**Comment by gonzalezreal** [comment]
MarkdownUI 2 supports text selection via the `.textSelection()` modifier.

**Comment by laike9m** [comment]
Wonder if it's possible to get the text that user currently selects?
