### ISSUE TITLE
Style enhancements for header font and spacing between list items

### ISSUE THREAD

**Issue by jefferythomas** [gonzalezreal/swift-markdown-ui#98]
Here are a couple of enhancements that have been an issue while using MarkdownUI.

* Add a feature to provide more control over the font used for headers
* Add a feature to control the space between list items

**Comment by gonzalezreal** [comment]
Hi @jefferythomas and @emartinson,

Please take a look at the latest release:
https://github.com/gonzalezreal/swift-markdown-ui/releases/tag/2.0.0

This version is a game-changer in terms of styling. You can do what you requested and much more.
